variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

test:
  stage: test
  image: python:3.8
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - make
  cache:
    paths:
      - .cache/pip
      - ~/.cache/black


# vim: sw=2 ts=2:
