variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

test:
  stage: test
  image: python:3.8
  services:
    - name: postgres
      alias: source
    - name: postgres
      alias: target
  before_script:
    - pip install -r requirements-dev.txt -r requirements.in
  script:
    - make PYTESTARGS='--junit-xml junit.xml'
  cache:
    paths:
      - .cache/pip
      - ~/.cache/black
  artifacts:
    reports:
      junit:
        - junit.xml
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+)%/'


# vim: sw=2 ts=2:
